INSERT INTO `#__osmembership_configs` (`id`, `config_key`, `config_value`) VALUES
(1, 'registration_integration', '0'),
(2, 'send_activation_email', '0'),
(3, 'from_name', ''),
(4, 'from_email', ''),
(5, 'notification_emails', ''),
(6, 'auto_generate_membership_id', '0'),
(7, 'membership_id_start_number', '1000'),
(8, 'show_login_box_on_subscribe_page', '1'),
(9, 'cb_integration', '0'),
(10, 'enable_captcha', '0'),
(11, 'enable_tax', '0'),
(12, 'enable_coupon', '0'),
(13, 'enable_cardtypes', 'Visa,MasterCard,Discover,Amex'),
(14, 'allowed_file_types', ''),
(15, 'tax_rate', '10'),
(16, 'use_https', '0'),
(17, 'accept_term', '0'),
(18, 'fix_terms_and_conditions_popup', '0'),
(19, 'article_id', '0'),
(20, 'date_format', 'm-d-Y'),
(21, 'currency_symbol', '$'),
(22, 'decimals', '2'),
(23, 'dec_point', '.'),
(24, 'thousands_sep', ','),
(25, 'currency_position', '0'),
(26, 'number_columns', '3'),
(27, 'load_twitter_bootstrap_in_frontend', '1'),
(28, 'send_attachments_to_admin', '0'),
(29, 'default_country', 'United States'),
(30, 'activate_invoice_feature', '0'),
(31, 'send_invoice_to_customer', '0'),
(32, 'invoice_start_number', '1'),
(33, 'invoice_prefix', 'IV'),
(34, 'invoice_number_length', '5'),
(35, 'invoice_format', '<table width="100%" border="0" cellspacing="0" cellpadding="2">\r\n<tbody>\r\n<tr>\r\n<td align="left" width="100%">\r\n<table width="100%" border="0" cellspacing="0" cellpadding="2">\r\n<tbody>\r\n<tr>\r\n<td width="100%">\r\n<table style="width: 100%;" border="0" cellspacing="0" cellpadding="2">\r\n<tbody>\r\n<tr>\r\n<td align="left" valign="top" width="50%">\r\n<table style="width: 100%;" border="0" cellspacing="0" cellpadding="2">\r\n<tbody>\r\n<tr>\r\n<td align="left" width="50%">Company Name:</td>\r\n<td align="left">Ossolution Team</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">URL:</td>\r\n<td align="left">http://www.joomdonation.com</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Phone:</td>\r\n<td align="left">84-972409994</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">E-mail:</td>\r\n<td align="left">contact@joomdonation.com</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Address:</td>\r\n<td align="left">Lang Ha - Ba Dinh - Ha Noi</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td align="right" valign="middle" width="50%"><img src="media/com_osmembership/invoice_logo.png" style="border: 0;" /></td>\r\n</tr>\r\n<tr>\r\n<td colspan="2" align="left" width="100%">\r\n<table style="width: 100%;" border="0" cellspacing="0" cellpadding="2">\r\n<tbody>\r\n<tr>\r\n<td align="left" valign="top" width="50%">\r\n<table style="width: 100%;" border="0" cellspacing="0" cellpadding="2">\r\n<tbody>\r\n<tr>\r\n<td style="background-color: #d6d6d6;" colspan="2" align="left">\r\n<h4 style="margin: 0px;">Customer Information</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Name:</td>\r\n<td align="left">[NAME]</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Company:</td>\r\n<td align="left">[ORGANIZATION]</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Phone:</td>\r\n<td align="left">[PHONE]</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Email:</td>\r\n<td align="left">[EMAIL]</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Address:</td>\r\n<td align="left">[ADDRESS], [CITY], [STATE], [COUNTRY]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td align="left" valign="top" width="50%">\r\n<table style="width: 100%;" border="0" cellspacing="0" cellpadding="2">\r\n<tbody>\r\n<tr>\r\n<td style="background-color: #d6d6d6;" colspan="2" align="left">\r\n<h4 style="margin: 0px;">Invoice Information</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Invoice Number:</td>\r\n<td align="left">[INVOICE_NUMBER]</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Invoice Date:</td>\r\n<td align="left">[INVOICE_DATE]</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%">Invoice Status:</td>\r\n<td align="left">[INVOICE_STATUS]</td>\r\n</tr>\r\n<tr>\r\n<td align="left" width="50%"> </td>\r\n<td align="left"> </td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style="background-color: #d6d6d6;" colspan="2" align="left">\r\n<h4 style="margin: 0px;">Order Items</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td colspan="2" align="left" width="100%">\r\n<table width="100%" border="0" cellspacing="0" cellpadding="2">\r\n<tbody>\r\n<tr>\r\n<td align="left" valign="top" width="10%">#</td>\r\n<td align="left" valign="top" width="60%">Name</td>\r\n<td align="right" valign="top" width="20%">Price</td>\r\n<td align="left" valign="top" width="10%">Sub Total</td>\r\n</tr>\r\n<tr>\r\n<td align="left" valign="top" width="10%">[ITEM_QUANTITY]</td>\r\n<td align="left" valign="top" width="60%">[ITEM_NAME]</td>\r\n<td align="right" valign="top" width="20%">[ITEM_AMOUNT]</td>\r\n<td align="left" valign="top" width="10%">[ITEM_SUB_TOTAL]</td>\r\n</tr>\r\n<tr>\r\n<td colspan="3" align="right" valign="top" width="90%">Discount :</td>\r\n<td align="left" valign="top" width="10%">[DISCOUNT_AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td colspan="3" align="right" valign="top" width="90%">Subtotal :</td>\r\n<td align="left" valign="top" width="10%">[SUB_TOTAL]</td>\r\n</tr>\r\n<tr>\r\n<td colspan="3" align="right" valign="top" width="90%">Tax :</td>\r\n<td align="left" valign="top" width="10%">[TAX_AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td colspan="3" align="right" valign="top" width="90%">Total :</td>\r\n<td align="left" valign="top" width="10%">[TOTAL_AMOUNT]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>');